version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_management
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    image: node:20
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/expense_management?schema=public
      - PORT=8888
      - JWT_SECRET=docker-development-secret-key
      - JWT_EXPIRES_IN=7d
      - LOG_LEVEL=info
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"
    ports:
      - "8888:8888"

  client:
    image: node:20
    working_dir: /app
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8888/graphql
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  db_data:
