version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    image: node:20
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/appdb
    depends_on:
      - db
    command: sh -c "npm install && npm run build && npm start"
    ports:
      - "5000:5000"

  client:
    image: node:20
    working_dir: /app
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run build && npm run preview"
    ports:
      - "5173:4173"

volumes:
  db_data:
